# AETHER-OS Core Linux Declarative Configuration
# Reifies the spatial AI-native desktop environment as an immutable NixOS system profile.

{ config, pkgs, lib, ... }:

{
  imports = [
    # Include hardware scans automatically generated by target installation seat
    ./hardware-configuration.nix
  ];

  # ==========================================
  # 1. BOOT SYSTEM & SILENT INITIALIZATION
  # ==========================================
  boot = {
    kernelPackages = pkgs.linuxPackages_latest;
    
    # Configure custom Systemd-boot loader with clean parameters
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
      timeout = 0; # Instant transition into bootloader target
    };

    # Absolute quiet boot settings for cinematic transition
    consoleLogLevel = 0;
    initrd.verbose = false;
    kernelParams = [
      "quiet"
      "splash"
      "boot.shell_on_fail"
      "loglevel=3"
      "rd.systemd.show_status=false"
      "rd.udev.log_level=3"
      "udev.log_priority=3"
      "vt.global_cursor_default=0"
    ];

    # Cinematic graphical boot splash using Plymouth
    plymouth = {
      enable = true;
      theme = "aether-boot";
      themePackages = [
        # Custom derivation containing AETHER cinematic Plymouth assets
        (pkgs.callPackage ./aether-boot-theme.nix {})
      ];
    };
  };

  # ==========================================
  # 2. FILE SYSTEM & SECURITY IMMUTABILITY
  # ==========================================
  fileSystems = {
    "/" = {
      device = "none";
      fsType = "tmpfs";
      options = [ "defaults" "size=4G" "mode=755" ]; # Ephemeral root for security
    };
    "/nix" = {
      device = "/dev/disk/by-label/nixos_nix";
      fsType = "ext4";
      neededForBoot = true;
    };
    "/persist" = {
      device = "/dev/disk/by-label/nixos_persist";
      fsType = "ext4";
      neededForBoot = true;
    };
  };

  # Bind mount directories needing persistence across boots
  environment.persistence."/persist" = {
    directories = [
      "/var/log"
      "/var/lib/bluetooth"
      "/var/lib/NetworkManager"
      "/etc/nixos"
    ];
    files = [
      "/etc/machine-id"
    ];
  };

  # ==========================================
  # 3. GPU HARDWARE ACCELERATION
  # ==========================================
  hardware = {
    graphics = {
      enable = true;
      enable32Bit = true;
      extraPackages = with pkgs; [
        mesa.drivers
        intel-media-driver
        vaapiIntel
        vaapiVdpau
        libvdpau-va-gl
        amdvlk
      ];
    };
  };

  # ==========================================
  # 4. SYSTEM SERVICES & ENVIRONMENT
  # ==========================================
  networking = {
    hostName = "aether-os";
    networkmanager.enable = true;
  };

  time.timeZone = "UTC";
  i18n.defaultLocale = "en_US.UTF-8";

  # Audio nervous system configuration using low-latency PipeWire
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    jack.enable = true;
  };

  # Optimized system thermal and power scaling profiles
  services.power-profiles-daemon.enable = true;
  services.thermald.enable = true;

  # Enable dynamic dbus messaging bus
  services.dbus.enable = true;

  # ==========================================
  # 5. USER SESSION & AUTHENTICATION (greetd)
  # ==========================================
  services.greetd = {
    enable = true;
    settings = {
      default_session = {
        # Secure spatial desktop booting straight into AETHER's custom Wayland compositor
        command = "${pkgs.dbus}/bin/dbus-run-session ${pkgs.aether-shell}/bin/aether-compositor -- ${pkgs.aether-shell}/bin/aether-shell-launcher";
        user = "aether";
      };
    };
  };

  # Define Aether core system user
  users.users.aether = {
    isNormalUser = true;
    extraGroups = [ "wheel" "video" "audio" "networkmanager" "input" ];
    initialPassword = "aether"; # Ephemeral / overridden by Lock Screen setup
  };

  # ==========================================
  # 6. SYSTEM PACKAGES
  # ==========================================
  environment.systemPackages = with pkgs; [
    git
    vim
    curl
    wget
    wayland
    libinput
    libxkbcommon
    seatd
    dbus        # IPC bus communication
    pipewire    # Low-latency multimedia framework
    wireplumber # Pipewire controller
    vulkan-loader
    vulkan-tools
  ];

  # Nix configuration optimization
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  system.stateVersion = "26.05";
}
